apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: compositegrappleapplicationsets.grsf.grpl.io
    provider: gras
  name: gras.grsf.grpl.io
spec:
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: CompositeGrappleApplicationSet
  mode: Pipeline
  pipeline:
  # - step: license-check
  #   functionRef:
  #     name: grpl-grsf-lic
  #   input:
  #     apiVersion: template.fn.crossplane.io/v1beta1
  #     kind: Input
  #     email: "info@grapple-solutions.com"
  - step: transform-values
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: spec.claimRef.name
          toFieldPath: spec.asname
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: spec.asname
          toFieldPath: status.calculatedMapi
          transforms:
            - type: string
              string:
                fmt: "%s-grapi-mapi"
  - step: gras-logic
    functionRef:
      name: grpl-gras
  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
