apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gras.grsf.grpl.io
  labels:
    crossplane.io/xrd: compositegrappleapplicationsets.grsf.grpl.io
    provider: gras
spec:
  # writeConnectionSecretsToNamespace: grpl-system
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: CompositeGrappleApplicationSet
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: gras-release
            base:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              metadata:
                annotations: 
                  crossplane.io/external-name: # patched
              spec:
                forProvider:
                  chart:
                    name: gras
                    repository: oci://public.ecr.aws/p7h7z5g3
                    version: 0.2.8
                  namespace: # patched
                  values:
                    name: # patched
                    asname: ""
                    grasversion: # patched
                    grapis: []
                    gruims: []
                  # set: 
                  #   - name: externalDatabase.host
                  #     valueFrom: 
                  #       secretKeyRef: 
                  #         name: 
                  #         namespace: grpl-system
                  #         key: endpoint
                  #   - name: externalDatabase.user
                  #     valueFrom: 
                  #       secretKeyRef: 
                  #         name: 
                  #         namespace: grpl-system
                  #         key: username
                  #   - name: externalDatabase.password
                  #     valueFrom: 
                  #       secretKeyRef: 
                  #         name: 
                  #         namespace: grpl-system
                  #         key: password
                writeConnectionSecretToRef: 
                  namespace: grpl-test
                  name: myrelease-secret
                providerConfigRef: 
                  # name: providerconfigs.helm.crossplane.io/helm-provider-config
                  name: helm-provider-config
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.claimRef.namespace
                toFieldPath: spec.forProvider.namespace
                policy:
                  fromFieldPath: Required
              - type: FromCompositeFieldPath
                fromFieldPath: spec.claimRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                policy:
                  fromFieldPath: Required
              - type: FromCompositeFieldPath
                fromFieldPath: spec.claimRef.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
                policy:
                  fromFieldPath: Required
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-gras"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.claimRef.name
                toFieldPath: spec.forProvider.values.name
                policy:
                  fromFieldPath: Required
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-gras"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.claimRef.name
                toFieldPath: spec.forProvider.values.asname
              - type: FromCompositeFieldPath
                fromFieldPath: spec.grasversion
                toFieldPath: spec.forProvider.values.grasversion
              - type: FromCompositeFieldPath
                fromFieldPath: spec.customheader
                toFieldPath: spec.forProvider.values.customheader
              - type: FromCompositeFieldPath
                fromFieldPath: spec.autoscaling
                toFieldPath: spec.forProvider.values.autoscaling
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resources.resourcesNpmMem
                toFieldPath: spec.forProvider.values.resourcesNpmMem
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resources.runimages.spec
                toFieldPath: spec.forProvider.values.resources.runimages.spec
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resources.deployimages.spec
                toFieldPath: spec.forProvider.values.resources.deployimages.spec
              - type: FromCompositeFieldPath
                fromFieldPath: spec.dev
                toFieldPath: spec.forProvider.values.dev
              - type: FromCompositeFieldPath
                fromFieldPath: spec.grapis
                toFieldPath: spec.forProvider.values.grapis
              - type: FromCompositeFieldPath
                fromFieldPath: spec.gruims
                toFieldPath: spec.forProvider.values.gruims


              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.clusterdomain
              #   toFieldPath: spec.forProvider.values.clusterdomain
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ingress
              #   toFieldPath: spec.forProvider.values.ingress
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.ssl
              #   toFieldPath: spec.forProvider.values.ssl
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.sslissuer
              #   toFieldPath: spec.forProvider.values.sslissuer
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.sslissuer
              #   toFieldPath: spec.forProvider.values.sslissuer
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.buildimages
              #   toFieldPath: spec.forProvider.values.buildimages
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.buildimagecache
              #   toFieldPath: spec.forProvider.values.buildimagecache
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.runimages
              #   toFieldPath: spec.forProvider.values.runimages
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.deployimages
              #   toFieldPath: spec.forProvider.values.deployimages
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.imagetag
              #   toFieldPath: spec.forProvider.values.imagetag
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.beimage
              #   toFieldPath: spec.forProvider.values.beimage


              # does it work, if this is disabled?
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.claimRef.beimagetag
              #   toFieldPath: spec.forProvider.values.beimagetag
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.cacheconfigs
              #   toFieldPath: spec.forProvider.values.cacheconfigs
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.fuzzysearch
              #   toFieldPath: spec.forProvider.values.fuzzysearch


              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.translations
              #   toFieldPath: spec.forProvider.values.translations
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.apiregistry
              #   toFieldPath: spec.forProvider.values.apiregistry
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.graphql
              #   toFieldPath: spec.forProvider.values.graphql
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.monitoring
              #   toFieldPath: spec.forProvider.values.monitoring
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.discoveredrepos
              #   toFieldPath: spec.forProvider.values.discoveredrepos
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.externalsecrets
              #   toFieldPath: spec.forProvider.values.externalsecrets

              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.datasources
              #   toFieldPath: spec.forProvider.values.datasources
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.discoveries
              #   toFieldPath: spec.forProvider.values.discoveries
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.models
              #   toFieldPath: spec.forProvider.values.models
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.relations
              #   toFieldPath: spec.forProvider.values.relations
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.serviceproviders
              #   toFieldPath: spec.forProvider.values.serviceproviders
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.openapis
              #   toFieldPath: spec.forProvider.values.openapis
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.restcruds
              #   toFieldPath: spec.forProvider.values.restcruds
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.repositories
              #   toFieldPath: spec.forProvider.values.repositories
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.controllers
              #   toFieldPath: spec.forProvider.values.controllers
              # - type: FromCompositeFieldPath
              #   fromFieldPath: spec.patches
              #   toFieldPath: spec.forProvider.values.patches


          # - name: mypod
          #   base:
          #     apiVersion: kubernetes.crossplane.io/v1alpha1
          #     kind: Object
          #     spec:
          #       forProvider:
          #         manifest:
          #           apiVersion: v1
          #           kind: Pod
          #           metadata:
          #             name: mypod
          #             namespace: grpl-test
          #           spec:
          #             containers:
          #             - image: nginx:latest
          #               name: mypod
          #       writeConnectionSecretsToRef: 
          #         namespace: grpl-test
          #         name: mypod-secret
          #       providerConfigRef: 
          #         # name: providerconfigs.kubernetes.crossplane.io/kubernetes-provider
          #         name: kubernetes-provider
          #   patches:
          #     - type: FromCompositeFieldPath
          #       fromFieldPath: metadata.namespace
          #       toFieldPath: metadata.namespace
