---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    crossplane.io/xrd: compositegrappleagents.grsf.grpl.io
    provider: gragent
  name: gragent.grsf.grpl.io
spec:
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: CompositeGrappleAgent
  mode: Pipeline
  pipeline:
  - functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - base:
          apiVersion: helm.crossplane.io/v1beta1
          kind: Release
          metadata:
            annotations:
              crossplane.io/external-name: null
          spec:
            forProvider:
              chart:
                name: gragent
                repository: oci://public.ecr.aws/p7h7z5g3
                version: 0.1.19
              namespace: null
              values:
                replicaCount: 1
                image:
                  repository: grpl/gragent
                  tag: "0.1.19"
                config: {}
            providerConfigRef:
              name: helm-provider-config
            writeConnectionSecretToRef:
              name: null
              namespace: null
        name: resource-0
        patches:
        - fromFieldPath: spec.claimRef.namespace
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.namespace
          policy:
            fromFieldPath: Required
          toFieldPath: spec.writeConnectionSecretToRef.namespace
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.name
          policy:
            fromFieldPath: Required
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
          - string:
              fmt: "%s-gragent-secret"
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.name
          policy:
            fromFieldPath: Required
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          transforms:
          - string:
              fmt: '%s-gragent'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.name
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.values.name
          transforms:
          - string:
              fmt: '%s-gragent'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.claimRef.name
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.values.config.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.replicaCount
          toFieldPath: spec.forProvider.values.replicaCount
          type: FromCompositeFieldPath
        - fromFieldPath: spec.image
          toFieldPath: spec.forProvider.values.image
          type: FromCompositeFieldPath
        - fromFieldPath: spec.service
          toFieldPath: spec.forProvider.values.service
          type: FromCompositeFieldPath
        - fromFieldPath: spec.lookup
          toFieldPath: spec.forProvider.values.lookup
          type: FromCompositeFieldPath
        - fromFieldPath: spec.ingress
          toFieldPath: spec.forProvider.values.ingress
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resources
          toFieldPath: spec.forProvider.values.resources
          type: FromCompositeFieldPath
        - fromFieldPath: spec.config
          toFieldPath: spec.forProvider.values.config
          type: FromCompositeFieldPath
        - fromFieldPath: spec.secrets
          toFieldPath: spec.forProvider.values.secrets
          type: FromCompositeFieldPath