apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: grsf.grsf.grpl.io
  labels:
    crossplane.io/xrd: compositegrapplesolutionframeworks.grsf.grpl.io
    provider: grsf
spec:
  # writeConnectionSecretsToNamespace: grpl-system
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: CompositeGrappleSolutionFramework
